### ISSUE TITLE
Configuration items

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-sirf#4]
- [x] Update site icon/favicon to 
![FullColor_1280x1024_72dpi](https://user-images.githubusercontent.com/48263361/74964513-2ca15280-53d9-11ea-9909-26ec787a63c2.png)
- [x] Add donate button to right sidebar on Homepage (largo donate button)
- [x] re-enable Largo donate button in top bar
- [ ] remove FB from like/share options

**Comment by joshdarby** [comment]
@MirandaEcho All of these are done, except the FB one. I don't see FB sharing/icons enabled on their site.
